baseURL = "http://maklog.io/"
languageCode = "en-us"
title = "Mak's blog"
theme = "minimal"
disqusShortname = "mak"
googleAnalytics = "UA-108378118-1"
DefaultContentLanguage = "en"

[params]
    author = "Marcos Entenza"
    description = "Mak's Personal blog"
    githubUsername = "#makentenza"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Sarala"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "diff", "ini", "json", "shell", "markdown"]

[Languages]
[Languages.en]
weight = 1

[Languages.es]
weight = 2

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

[[menu.icon]]
    url = "https://github.com/makentenza/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/makentenza/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/makentenza/"
    name = "linkedin"
    weight = 4
